import { NextRequest, NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth'
import { createAdminClient } from '@/lib/supabase.server'
import { getPracticeSettings, buildFullDocumentHtml } from '@/lib/document'

export async function POST(req: NextRequest) {
  const auth = await requireRole(['doctor', 'admin'])
  if (auth.error) return auth.error

  const { to, report_html, doctor_report, patient_name, patient_id, id } = await req.json()

  if (!to || !to.includes('@') || !to.includes('.')) {
    return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
  }
  if (!id || !patient_name || !patient_id) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  const practiceSettings = await getPracticeSettings()
  const fullHtml = buildFullDocumentHtml({ practiceSettings, report_html, doctor_report, patient_name, patient_id })

  const htmlDocx = await import('html-docx-js/dist/html-docx')
  const docxBuffer: Buffer = htmlDocx.default.asBlob(fullHtml, {
    orientation: 'portrait',
    margins: { top: 1440, right: 1080, bottom: 1440, left: 1080 },
  })

  const base64 = Buffer.from(await docxBuffer.arrayBuffer()).toString('base64')

  const { Resend } = await import('resend')
  const resend = new Resend(process.env.RESEND_API_KEY)
  const fromName = practiceSettings.practice_name || 'Bone Density Clinic'

  await resend.emails.send({
    from: process.env.FROM_EMAIL ?? 'noreply@yourpractice.com',
    to,
    subject: `Bone density report — ${patient_name}`,
    html: `<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:32px 16px">
      <h2 style="color:#1e3a5f">${fromName}</h2>
      <p style="color:#475569">Please find attached the bone density assessment report for <strong>${patient_name}</strong> (ID: ${patient_id}).</p>
      <p style="color:#94a3b8;font-size:12px;margin-top:24px">This report was generated by the ${fromName} reporting system.</p>
    </div>`,
    attachments: [{ filename: `DXA_Report_${patient_id}.docx`, content: base64 }],
  })

  const admin = createAdminClient()
  await admin.from('audit_log').insert({
    user_id: auth.user.id,
    action: 'doctor_emailed',
    submission_id: id,
    detail: { recipient: to },
  })

  return NextResponse.json({ success: true })
}
